[project]
name = "plugin-lightgbm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ritsuki1227", email = "ritsuki1227@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "base",
    "lightgbm>=4.6.0",
    "pandas>=2.2.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
base = { workspace = true }
