site_name: Factrainer
site_url: https://ritsuki1227.github.io/factrainer/
repo_url: https://github.com/ritsuki1227/factrainer/
repo_name: ritsuki1227/factrainer
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - API Reference:
    - Overview: reference/index.md
    - Core:
      - Overview: reference/core/index.md
      - CvModelContainer: reference/core/cvmodelcontainer.md
      - SingleModelContainer: reference/core/singlemodelcontainer.md
      - EvalMode: reference/core/evalmode.md
      - PredMode: reference/core/predmode.md
      - SplittedDatasetsIndices: reference/core/splitteddatasetsindices.md
    - LightGBM:
      - Overview: reference/lightgbm/index.md
      - LgbDataset: reference/lightgbm/lgbdataset.md
      - LgbTrainConfig: reference/lightgbm/lgbtrainconfig.md
      - LgbPredictConfig: reference/lightgbm/lgbpredictconfig.md
      - LgbModelConfig: reference/lightgbm/lgbmodelconfig.md
      - LgbModel: reference/lightgbm/lgbmodel.md
    - Scikit-learn:
      - Overview: reference/sklearn/index.md
      - SklearnDataset: reference/sklearn/sklearndataset.md
      - SklearnTrainConfig: reference/sklearn/sklearntrainconfig.md
      - SklearnPredictConfig: reference/sklearn/sklearnpredictconfig.md
      - SklearnModelConfig: reference/sklearn/sklearnmodelconfig.md
      - SklearnModel: reference/sklearn/sklearnmodel.md
      - SklearnPredictMethod: reference/sklearn/sklearnpredictmethod.md
    - XGBoost: reference/xgboost/index.md
    - CatBoost: reference/catboost/index.md

plugins:
- search
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    default_handler: python
    handlers:
      python:
        options:
          annotations_path: "brief"
          docstring_style: "numpy"
          docstring_section_style: "table"
          filters: 
          - "!^_"
          - "^__"
          inherited_members: true
          members: true
          merge_init_into_class: true
          members_order: "source"
          modernize_annotations: true
          separate_signature: true
          show_bases: false  # Hide implemented interfaces
          show_category_heading: true
          show_if_no_docstring: false
          show_root_heading: true
          show_root_toc_entry: true
          show_root_full_path: false
          show_signature: true
          show_signature_annotations: true
          show_source: false
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_submodules: false
          signature_crossrefs: true
          unwrap_annotated: true

extra:
  version:
    provider: mike
    alias: true
    default: stable
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ritsuki1227/factrainer

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
