[project]
name = "factrainer-lightgbm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "ritsuki1227", email = "ritsuki1227@gmail.com" }]
requires-python = ">=3.12"
dependencies = ["factrainer-core", "lightgbm>=4.6.0", "pandas>=2.2.3"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["factrainer/lightgbm"]

[tool.uv.sources]
factrainer-core = { workspace = true }
