[project]
name = "factrainer-catboost"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "ritsuki1227", email = "ritsuki1227@gmail.com" }]
requires-python = ">=3.12"
dependencies = ["catboost>=1.2.7", "factrainer-core"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["factrainer/catboost"]

[tool.uv.sources]
factrainer-core = { workspace = true }
